name: Node.js Package
on:
  push:
    branches: [ master ]   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://npm.pkg.github.com'
    - run: yarn
    - run: yarn build
    - run: yarn semantic-release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}